#version 450

layout(set = 0,binding = 0) buffer NumbersBuffer{
    int numbers[];
};

int isPrime(int n)
{
    // Corner case
    if (n <= 1)
        return 0;
  
    // Check from 2 to n-1
    for (int i = 2; i <= n/2; i++)
        if (n % i == 0)
            return 0;
  
    return n;
}

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;


void main()
{
    uint index = gl_GlobalInvocationID.x;
    numbers[index] = isPrime(numbers[index]);
}